
private["_Objeckt","_House"];

_Objeckt = typeOf _this;
_House = _this;
sleep (Random 2);
switch (_Objeckt) do {
	     case "Land_vn_cave_01"                   : {
                                                     ["klein","sichtbar"   ,_House,[  1.15 , -3.71 ,  0.07 ],339] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","sichtbar"   ,_House,[ -3.22 , -4.58 ,  0.06 ],42 ] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","sichtbar"   ,_House,[ -2.84 , -2.52 ,  6.85 ],177] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","sichtbar"   ,_House,[ -2.17 ,  1.24 , 13.21 ],9  ] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["waffe","sichtbar"   ,_House,[ -2.21 , -4.71 , 21.65 ],187] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item" ,"sichtbar"   ,_House,[ -6.25 ,  3.48 , 13.19 ],355] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
	     case "Land_vn_cave_01_01"                : {["klein","unsichtbar" ,_House,[  2.31 , -2.67 ,  1.00 ],230] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar" ,_House,[ -4.29 , -4.38 ,  1.00 ],480] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar" ,_House,[ -0.87 , -2.70 ,  7.85 ],192] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar" ,_House,[ -6.11 , -2.51 ,  7.85 ],188] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar" ,_House,[  0.84 ,  1.93 ,  7.84 ],61 ] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar" ,_House,[ -5.76 ,  0.23 , 14.21 ],244] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
		 case "Land_vn_cave_02"                   : {["klein","sichtbar"   ,_House,[  2.31 , -2.67 ,  1.00 ],230] call ACP_fnc_erzeugen ; sleep 2;  
                                                     ["klein","sichtbar"   ,_House,[ -4.29 , -4.38 ,  1.00 ],480] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -6.73 ,  1.63 ,  7.85 ],308] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[ -5.62 ,  2.23 ,  7.55 ],357] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[ -1.81 ,  2.20 , 13.21 ],6  ] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_cave_02_01"                : {["klein","unsichtbar" ,_House,[  2.31 , -2.67 ,  1.00 ],230] call ACP_fnc_erzeugen ; sleep 2;  
                                                     ["klein","unsichtbar" ,_House,[ -4.29 , -4.38 ,  1.00 ],480] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ 0.892 ,  0.49 ,  7.85 ],87 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -4.29 ,  1.79 ,  7.85 ],2  ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -6.54 ,  1.65 ,  7.85 ],314] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","unsichtbar" ,_House,[ -3.42 , -2.54 ,  7.85 ],271] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","unsichtbar" ,_House,[ -3.25 , -0.35 , 14.21 ],345] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_cave_03"                   : {["klein","sichtbar"   ,_House,[  1.15 , -3.71 ,  0.07 ],339] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","sichtbar"   ,_House,[ -3.22 , -4.58 ,  0.06 ],42 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[ -5.13 ,  2.89 ,  1.28 ],245] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_cave_03_01"                : {["klein","unsichtbar" ,_House,[  2.31 , -2.67 ,  1.00 ],230] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -4.29 , -4.38 ,  1.00 ],480] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -0.31 ,  2.27 ,  6.85 ],2  ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -5.68 ,  2.23 ,  6.85 ],357] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -3.81 ,  3.37 , 14.21 ],6  ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","unsichtbar" ,_House,[ -2.02 , -1.06 , 14.21 ],93 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[ -6.19 , -0.75 , 13.90 ],273] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[ -2.48 , 3.165 , 13.90 ],37 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_cave_04"                   : {["klein","sichtbar"   ,_House,[  1.15 , -3.71 ,  0.07 ],339] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","sichtbar"   ,_House,[ -3.22 , -4.58 ,  0.06 ],42 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[ -2.84 , -2.52 ,  6.85 ],177] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[ -2.17 ,  1.24 , 13.21 ],9  ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[ -2.21 , -4.71 , 21.65 ],187] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[ -6.25 ,  3.48 , 13.19 ],355] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","unsichtbar" ,_House,[ -5.87 ,  1.65 ,  7.84 ],270] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_cave_04_01"                : {["klein","unsichtbar" ,_House,[  2.31 , -2.67 ,  1.00 ],230] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[ -4.29 , -4.38 ,  1.00 ],48 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","unsichtbar" ,_House,[ -5.87 ,  1.65 ,  7.84 ],270] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[ -4.21 , -1.66 ,  7.60 ],270] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[ -6.16 , -0.75 ,  13.9 ],277] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[ -2.21 , -4.71 ,  21.6 ],187] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };          
         case "Land_vn_cave_05"                   : {["gross","sichtbar"   ,_House,[   8.2 , -9.30 ,     0 ],81 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[   9.1 ,  8.20 ,     0 ],49 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","sichtbar"   ,_House,[  -1.2 ,  0.70 ,     0 ],16 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[   4.0 , -1.50 ,     0 ],107] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[   0.1 , -1.50 ,     0 ],301] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_cave_06"                   : {["gross","sichtbar"   ,_House,[   3.2 , -4    ,     0 ],  0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[   8.3 , -3.3  ,     0 ],174] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","sichtbar"   ,_House,[   0.5 , -12.7 ,     0 ],90 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[  -8.1 ,  14.1 ,     0 ],335] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[  -6.3 ,  12.2 ,     0 ],203] call ACP_fnc_erzeugen ; sleep 2; 
                                                    }; 
         case "Land_vn_cave_07"                   : {["gross","sichtbar"   ,_House,[   -14 ,  0    ,  10.3 ],258] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["gross","sichtbar"   ,_House,[   7.3 ,  -1   ,  10   ],79 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","sichtbar"   ,_House,[   -11 ,  0    ,  10   ],359] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["waffe","sichtbar"   ,_House,[   4.1 ,  0.3  ,  9.6  ], 4 ] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["item" ,"sichtbar"   ,_House,[   6.7 ,  -2.8 ,  9.6  ],-95] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_hut_03"                    : {["klein_zivil","zivil",_House,[   1.0 ,  -2.3 ,  -0.50],  0] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_hut_village_02"            : {["Gross_zivil","zivil",_House,[  -2.71,   2.56,   0.32],270] call ACP_fnc_erzeugen ; 
                                                    }; 
         case "Land_vn_hut_village_01"            : {["Gross_zivil","zivil",_House,[  -3.57,  1.89 ,   0.14],272] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_hut_04"                    : {["klein_zivil","zivil",_House,[   0.92,  -1.51,   1.10],124] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_hut_08"                    : {["klein_zivil","zivil",_House,[   0.92,  -1.51,   1.00],124] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_hut_07"                    : {["klein_zivil","zivil",_House,[   3.34,   4.39,   0.84],  1] call ACP_fnc_erzeugen ; 
                                                    };                                                                                                                                                                                                                                                                       
	     case "Land_vn_hut_02"                    : {["klein_zivil","zivil",_House,[  -0.77,   2.47,   0.82],272] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hut_06"                    : {["klein_zivil","zivil",_House,[  0.810,   2.18,   0.82],270] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hut_05"                    : {["klein_zivil","zivil",_House,[  -1.24,  -1.85,   0.75],358] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hut_tower_03"              : {["klein_zivil","zivil",_House,[  -1.10,   0.45,   3.22],285] call ACP_fnc_erzeugen ;
	                                                }; 
	     case "Land_vn_hut_river_02"              : {["klein_zivil","zivil",_House,[   4.74,  -4.19,   1.95], 89] call ACP_fnc_erzeugen ;
	                                                }; 
	     case "Land_vn_hut_river_01"              : {["klein_zivil","zivil",_House,[  -2.96,  -5.93,   0.56], 13] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hut_river_03"              : {["Gross_zivil","zivil",_House,[  -1.22,  -3.20,   2.10],273] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hootch_02_03"              : {["klein","sichtbar"   ,_House,[   1.69,   3.27,   1.02], 11] call ACP_fnc_erzeugen ; 
	                                                };
	     case "Land_vn_hootch_02_02"              : {["klein","sichtbar"   ,_House,[   1.29,   3.67,   1.02],  2] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hootch_02_01"              : {["klein","unsichtbar" ,_House,[   2.50,  -1.89,   1.02],  0] call ACP_fnc_erzeugen ;
	                                                };
         case "Land_vn_hootch_02_11"              : {["klein","unsichtbar" ,_House,[   2.50,  -1.89,   1.02],  0] call ACP_fnc_erzeugen ;
	                                                };
	     case "Land_vn_hootch_01_01"              : {["klein","unsichtbar" ,_House,[   2.56,   3.10,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[  -2.58,  -0.76,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
	                                                 ["klein","unsichtbar" ,_House,[  -0.49,   2.10,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   0.46,  -1.71,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   2.29,  -0.68,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[  -2.32,  -2.83,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;   
	                                                }; 
	     case "Land_vn_hootch_01_11"              : {["klein","unsichtbar" ,_House,[   2.56,   3.10,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[  -2.58,  -0.76,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
	                                                 ["klein","unsichtbar" ,_House,[  -0.49,   2.10,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   0.46,  -1.71,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   2.29,  -0.68,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[  -2.32,  -2.83,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;   
	                                                };
	     case "Land_vn_hootch_01_12"              : {["klein","unsichtbar" ,_House,[  -2.31,   3.06,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   2.59,   3.04,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
	                                                 ["klein","unsichtbar" ,_House,[   0.53,   0.24,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;            
                                                     ["klein","unsichtbar" ,_House,[  -2.56,  -0.72,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[   2.18,  -0.65,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
         case "Land_vn_hootch_01_02"              : {["klein","unsichtbar" ,_House,[  -2.31,   3.06,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
	                                                 ["klein","unsichtbar" ,_House,[   2.59,   3.04,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
	                                                 ["klein","unsichtbar" ,_House,[   0.53,   0.24,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;            
                                                     ["klein","unsichtbar" ,_House,[  -2.56,  -0.72,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar" ,_House,[   2.18,  -0.65,   1.02],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
         case "Land_vn_hootch_01_03"              : {["klein","unsichtbar",_House,[-2.42, 0.26,1.52],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-0.65, 3.71,1.82],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-1.61, 3.78,1.82],0] call ACP_fnc_erzeugen ; sleep 2;
                                                    };  
         case "Land_vn_hootch_01_13"              : {["klein","unsichtbar",_House,[-2.42, 0.26,1.52],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-0.65, 3.71,1.82],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-1.61, 3.78,1.82],0] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
         case "Land_vn_hootch_02"                 : {["gross","sichtbar",_House,[-0.12,2.29,1.02],7] call ACP_fnc_erzeugen ; 
                                                    }; 
         case "Land_vn_barracks_04_02"            : {["klein","unsichtbar",_House,[1.65,-7.37,0.05],0] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_barracks_04_01"            : {["klein","unsichtbar",_House,[ 0.79,-6.48,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 2.84,-5.61,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[-2.94,-3.61,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[-0.89,-2.58,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 0.69,-2.53,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 2.78, 0.40,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 0.88, 1.53,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[-3.11, 0.33,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[-2.90, 2.48,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 2.95, 5.87,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                    };
         case "Land_vn_barracks_03_01"            : {["klein","unsichtbar",_House,[ 0.75,-8.99,0.15],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[-3.15,-8.05,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.64,-7.94,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-0.98,-5.06,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.91,-4.05,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.59,-1.85,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 0.76,-0.89,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.91, 2.05,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 0.90, 3.08,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.06, 2.09,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-2.67, 4.11,0.15],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 3.10, 6.11,0.15],0] call ACP_fnc_erzeugen ; sleep 2;
                                                    }; 
         case "Land_vn_barracks_03_02"            : {["Gewehr","sichtbar",_House,[-2.58,-9.99,0.15],228] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","sichtbar",_House,[ 3.06,-8.07,0.15], 90] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","sichtbar",_House,[ 2.90,-1.83,0.15], 90] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"sichtbar",_House,[-3.01, 0.95,0.15],280] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein" ,"sichtbar",_House,[ 2.91, 9.29,0.15], 93] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_barracks_03_03"            : {["gross" ,"sichtbar",_House,[ 2.47,-9.04,0.15], 96] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"sichtbar",_House,[-2.95, 9.05,0.15],272] call ACP_fnc_erzeugen ; sleep 2;
                                                    }; 
         case "Land_vn_barracks_03_04"            : {["klein","unsichtbar",_House,[-2.93,-6.23,0.15],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-2.29,-4.24,0.95],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-1.80,-3.05,0.95],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross","unsichtbar",_House,[-1.84,-1.30,0.95],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","sichtbar" ,_House,[ 2.70,-4.11,0.15],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","sichtbar" ,_House,[-0.73, 3.08,0.15],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item"  ,"sichtbar" ,_House,[-1.25, 7.76,0.83],203] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item"  ,"sichtbar" ,_House,[ 0.62,-7.73,0.83], 12] call ACP_fnc_erzeugen ; sleep 2;   
                                                    };
         case "Land_vn_barracks_02_01"            : {["klein","unsichtbar",_House,[ 0.02,-6.38,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 1.92,-5.57,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.90,-3.56,0.05],0] call ACP_fnc_erzeugen ; sleep 2;   
                                                     ["klein","unsichtbar",_House,[-1.73,-2.46,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-0.00,-2.40,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.82, 0.37,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.23, 0.38,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 0.06, 1.60,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.74, 2.58,0.05],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.07, 5.99,0.05],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein","unsichtbar",_House,[ 2.00, 7.26,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 0.05, 6.32,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.07, 3.59,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 0.04, 2.59,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-1.61, 2.34,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.78,-0.44,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-1.74,-1.71,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 2.02,-2.53,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[ 1.14,-3.88,2.54],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["klein","unsichtbar",_House,[-3.78,-5.96,2.54],0] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
         case "Land_vn_guardhouse_01"             : {["Gewehr","sichtbar" ,_House,[-0.80,-0.47,0.00],90] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item"  ,"sichtbar" ,_House,[-1.04, 0.53,0.85],90] call ACP_fnc_erzeugen ; sleep 2;
                                                    };
         case "Land_vn_hut_mont_05"               : {["Gross_zivil","zivil",_House,[-1.60, 1.46,1.08],291] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_hut_mont_02"               : {["Gross_zivil","zivil",_House,[-1.79,-0.74,0.54],236] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_hut_mont_03"               : {["klein_zivil","zivil",_House,[ 1.14, 2.60,1.68], 94] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_hut_mont_04"               : {["klein_zivil","zivil",_House,[ 0.70, 2.77,1.67], 95] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_hut_mont_01"               : {["klein_zivil","zivil",_House,[-0.74, 1.54,1.64], 83] call ACP_fnc_erzeugen ;
                                                    };
		 case "Land_vn_hut_old02"                 : {["klein","unsichtbar" ,_House,[-5.52, 0.25,1.00],  0] call ACP_fnc_erzeugen ; sleep 2;
		                                             ["Gross","unsichtbar" ,_House,[-3.44, 0.54,1.00],  0] call ACP_fnc_erzeugen ; sleep 2; 
                                            		}; 											
         case "Land_vn_house_small_02_f"          : {["Gross_zivil","zivil",_House,[-3.15,-1.42,0.16],306] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_slum_house03_f"            : {["Gross_zivil","zivil",_House,[ 3.02, 1.90,0.00],105] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_slum_house01_f"            : {["klein_zivil","zivil",_House,[ 1.06, 1.52,0.00], 51] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_shed_03_f"                 : {["klein_zivil","zivil",_House,[ 1.75,-0.66,0.15],101] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_shed_05_f"                 : {["Gross_zivil","zivil",_House,[ 0.95,-1.43,0.19],148] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_shed_02_f"                 : {["klein_zivil","zivil",_House,[ 0.71, 1.82,0.03],  0] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_shed_07_f"                 : {["Gross_zivil","zivil",_House,[ 1.00, 1.00,0.00],  0] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_slum_03_f"                 : {["Gross_zivil","zivil",_House,[-0.57, 3.65,0.61], 95] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_slum_01_f"                 : {["klein_zivil","zivil",_House,[ 4.72,-0.80,0.59], 91] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_slum_02_f"                 : {["Gross_zivil","zivil",_House,[-1.20,-3.29,0.56],181] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_05_01"     : {["gross","sichtbar" ,_House,[ 0.05,-0.58,0.00],180] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_06_01"     : {["gross","sichtbar" ,_House,[ 1.12, 0.51,0.00], 88] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_04_01"     : {["gross","sichtbar" ,_House,[ 2.96,-2.20,0.00],183] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item" ,"sichtbar" ,_House,[ 1.83,-2.57,2.93],193] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };                                                                                                                                                                                                                                                                                                                   
         case "Land_vn_b_trench_firing_01"        : {["gross","sichtbar" ,_House,[ 2.99, 0.61,0.00],148] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_bagbunker_large_f"         : {["gross","sichtbar" ,_House,[ 1.30, 0.50,0.17],  0] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_bagbunker_01_large_green_f": {["gross","sichtbar" ,_House,[ 1.30, 0.50,0.17],  0] call ACP_fnc_erzeugen ; 
                                                    }; 
         case "Land_vn_pillboxbunker_01_big_f"    : {["Gewehr","sichtbar",_House,[-1.58, 4.46,0.06], 93] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"sichtbar",_House,[ 0.48, 4.21,0.06],274] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_bagbunker_small_f"         : {["klein" ,"sichtbar",_House,[ 0.62,-0.65,0.00],155] call ACP_fnc_erzeugen ;
                                                    };                                                                                
         case "Land_vn_bagbunker_01_small_green_f": {["klein" ,"sichtbar",_House,[ 0.62,-0.65,0.00],155] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_pillboxbunker_01_hex_f"    : {["klein" ,"sichtbar",_House,[-2.25,-0.76,0.10], 87] call ACP_fnc_erzeugen ; 
                                                    };
         case "Land_vn_b_trench_bunker_01_01"     : {["klein","unsichtbar",_House,[-0.33, 2.83,0.50],  0] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_02_01"     : {["gross","sichtbar"  ,_House,[-1.12,-0.49,0.24],185] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_02_02"     : {["Gewehr","unsichtbar",_House,[ 0.40, 1.50,0.84],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"unsichtbar",_House,[-1.69, 1.70,0.84],0] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_b_trench_bunker_02_03"     : {["Gewehr","unsichtbar",_House,[ 0.40, 1.50,0.84],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"unsichtbar",_House,[-1.69, 1.70,0.84],0] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_b_trench_bunker_02_04"     : {["klein" ,"unsichtbar",_House,[ 1.58, 1.58,0.84],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","unsichtbar",_House,[-0.09, 2.79,0.84],0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["Gewehr","unsichtbar",_House,[ 0.03,-1.15,0.84],0] call ACP_fnc_erzeugen ; sleep 2;                                      
                                                    };
         case "Land_vn_b_trench_bunker_01_02"     : {["klein" ,"unsichtbar",_House,[-1.28, 2.41,0.60],0] call ACP_fnc_erzeugen ; sleep 2;  
                                                     ["Gewehr","unsichtbar",_House,[ 0.27, 0.23,0.84],0] call ACP_fnc_erzeugen ; sleep 2;                                            
                                                    };
         case "Land_vn_b_trench_bunker_03_01"     : {["gross" ,"sichtbar"  ,_House,[-2.65, 3.99,0.27],277] call ACP_fnc_erzeugen ;
                                                    };
         case "Land_vn_b_trench_bunker_03_02"     : {["gross" ,"unsichtbar",_House,[ 3.80,-0.68,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross" ,"unsichtbar",_House,[ 1.62, 0.24,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross" ,"unsichtbar",_House,[-1.45, 1.85,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross" ,"unsichtbar",_House,[-1.41,-0.68,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross" ,"unsichtbar",_House,[-4.09, 0.72,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["gross" ,"unsichtbar",_House,[-4.25,-1.66,1.10],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","unsichtbar",_House,[-2.27,-3.00,0.84],0] call ACP_fnc_erzeugen ; sleep 2;      
                                                    };
         case "Land_vn_b_trench_bunker_03_03"     : {["MediK" ,"unsichtbar",_House,[-1.79, 1.78,0.27], 0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Medi"  ,"sichtbar"  ,_House,[-4.08, 5.11,1.40],90] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["MediK" ,"sichtbar"  ,_House,[ 2.79, 1.00,0.27],89] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["Medi"  ,"sichtbar"  ,_House,[-4.15, 4.97,1.00],90] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_b_trench_bunker_03_04"     : {["gross" ,"unsichtbar",_House,[ 1.86,-0.65,1.00],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["klein" ,"unsichtbar",_House,[-4.15,-2.59,0.27],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item"  ,"sichtbar"  ,_House,[-2.37,-1.21,1.00],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["item"  ,"sichtbar"  ,_House,[ 0.65, 2.01,0.90],0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","unsichtbar",_House,[-1.00,-2.99,0.80],0] call ACP_fnc_erzeugen ; sleep 2;  
                                                    };
         case "Land_vn_b_trench_bunker_01_03"     : {["klein" ,"unsichtbar",_House,[-0.28, 2.82,0.60],  0] call ACP_fnc_erzeugen ; sleep 2;
                                                     ["Gewehr","unsichtbar",_House,[ 1.35, 0.08,0.60],  0] call ACP_fnc_erzeugen ; sleep 2; 
                                                     ["MediK" ,"sichtbar"  ,_House,[-1.44, 0.10,0.24],204] call ACP_fnc_erzeugen ; sleep 2; 
                                                    }; 
         case "Land_vn_tent_mash_01"              : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };                                              
         case "Land_vn_tent_mash_01_01"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };                                                      
         case "Land_vn_tent_mash_01_02"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };         
         case "Land_vn_tent_mash_01_03"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };          
         case "Land_vn_tent_mash_01_04"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };        
         case "Land_vn_tent_mash_02_01"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };                                                      
         case "Land_vn_tent_mash_02_02"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };         
         case "Land_vn_tent_mash_02_03"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };          
         case "Land_vn_tent_mash_02_04"           : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ; 
                                                    };                
         case "Land_vn_wf_field_hospital_east"    : {["Zelt","unsichtbar",_House,[0,0,0],0] call ACP_fnc_erzeugen ;
                                                    };                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                            
	                   default {};                         
	                   };
exit; 

  



 





















